on:
  push:
    branches:
      - "main"
  workflow_dispatch: { }

jobs:
  build-models:
    name: "Build demo models"
    runs-on: "ubuntu-latest"

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: "write"      # to deploy to Pages
      id-token: "write"   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: "github-pages"
      # url: "${{ steps.deployment.outputs.page_url }}"

    # WARNING: You also need to go to Settings > Pages and set the source to "GitHub Actions"

    steps:

      # Checkout your repository
      - uses: "actions/checkout@v4"

      # Optional: Install your preferred Python version and set up caches
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
          cache: "pip"

      # Optional: Install your preferred Python packages
      - run: "pip install -r demos/requirements.txt"

      # Run the action
      - uses: "./" # Yeicor/ocp-action@v<version>
        with:
          scripts: "demos/box.py|demos/cycloidal_gear.py|demos/parametric_enclosure.py|demos/build123d_tea_cup.py"
          # formats: "STL|STEP|AMF|SVG|TJS|DXF|VRML|VTP|3MF|GLTF"
          # website: "."
          # website-screenshot: "true"